version: '3.0'

services:
  mysql:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: 'epsiroot'
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./src/db/:/docker-entrypoint-initdb.d
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - '${DB_PORT}:3306'